---
debug: true
title: Yark
subtitle: Web 1.0 Done Right
owner: Trey Piepmeier
email: trey@treypiepmeier.com
password: password
domain: treypiepmeier.com

# You can safely leave the rest of these fields alone:
# ----------------------------------------------------
date_format: l F jS, Y
