---
debug: true
title: Yark
subtitle: Web 1.0 Done Right
owner: Trey Piepmeier
email: trey@example.com
password: password
domain: example.com
# php or haml
template_type: haml
stats:
  mint:
    # Example: /mint/
    location: /mint/
  google:
    # Example: UA-XXXXX-X
    account: UA-XXXXX-X

# You can safely leave the rest of these fields alone:
# ----------------------------------------------------
date_format: l F jS, Y
